// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SocialBar from '../components/SocialBar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocialBar />
        {/* Header */}
        <header className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-md shadow-sm">
          <nav className="container mx-auto px-6 py-4 flex justify-between items-center">
            <Link href="/">
              <span className="text-xl font-semibold">Khunakorn W.</span>
            </Link>
            <div className="space-x-6">
              <Link href="/about" className='button-70' role='button'>About</Link>
              <Link href="/projects" className='button-70'role='button'>Projects</Link>
              <Link href="/certificates">Certificates</Link>
              <Link href="/resume">Resume</Link>
              <Link href="/contact"className='button-70'role='button'>Contact</Link>
            </div>
          </nav>
        </header>

        {/* Main Content */}
        <main className="flex-1 container mx-auto px-6 py-12">
          {children}
        </main>

        {/* Footer */}
        <footer className="bg-gray-100 dark:bg-gray-900 text-center py-4">
          © {new Date().getFullYear()} Khunakorn Wongsriprasert
        </footer>
      </body>
    </html>
  );
}
